### Add one user
POST http://localhost:3000/user
content-type: application/json

{
    "person":1,
    "total_price":1000,
    "hostel_id":4,
    "room_id":8,
    "dp_date":"2023-10-13",
    "cb_date":"2023-10-20",
    "planet_id":4,
    "user_id":1   
}

### Get one user
GET http://localhost:3000/user

### Patch one user
PATCH http://localhost:3000/user
content-type: application/json

{
    "person":1,
    "total_price":1000,
    "hostel_id":4,
    "room_id":8,
    "dp_date":"2023-10-13",
    "cb_date":"2023-10-20",
    "planet_id":4,
    "user_id":1   
}


### Delete one user
DELETE http://localhost:3000/user

### Post user info to login
POST http://localhost:3000/user
content-type: application/json

{
    "person":1,
    "total_price":1000,
    "hostel_id":4,
    "room_id":8,
    "dp_date":"2023-10-13",
    "cb_date":"2023-10-20",
    "planet_id":4,
    "user_id":1   
}