### log one user
POST http://localhost:3000/user
content-type: application/json

{
    "mail":"ici le mail du user",
    "password":"ici le password"
}

### Get one user
GET http://localhost:3000/user/1

### Patch one user
PATCH http://localhost:3000/user
content-type: application/json

{
    "firstname":"le firstname",
    "lastname":"le lastname",
    "email":"lenewemail@.com" 
}

### Delete one user
DELETE http://localhost:3000/user/2

### Post user info to login
POST http://localhost:3000/user
content-type: application/json

{
    "firstname":"le firsname",
    "lastname":"lelastname",
    "password":"monpassword",
    "email":"email", 
}